### ISSUE TITLE
Add Training Code

### ISSUE THREAD

**Issue by HassanAbbas92** [ESanchezLozano/Action-Units-Heatmaps#2]
Great work ESanchezLozano
But could you please please add training code so I can trained with new AUs?
Thank You

**Comment by ESanchezLozano** [comment]
Due to licensing issues it is not possible to release the training code, I am afraid this is not on my hands as I would be very happy to release it. However, I believe the paper doesn't conceal any details for the sake of its reproducibility, so you should be able to reproduce it :)
